from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
import os

def generate_scam_report(report_id, report_data, output_dir):
    """
    Generates a professional security analysis PDF report.
    """
    os.makedirs(output_dir, exist_ok=True)
    filename = f"report_{report_id}.pdf"
    filepath = os.path.join(output_dir, filename)
    
    doc = SimpleDocTemplate(filepath, pagesize=letter)
    styles = getSampleStyleSheet()
    story = []

    # Custom Styles
    title_style = ParagraphStyle('Title', parent=styles['Heading1'], fontSize=24, spaceAfter=20, textColor=colors.HexColor("#4e54c8"))
    header_style = ParagraphStyle('Header', parent=styles['Heading2'], fontSize=16, spaceAfter=10, textColor=colors.HexColor("#1a1b3a"))
    grade_style = ParagraphStyle('Grade', parent=styles['Heading1'], fontSize=48, alignment=1, textColor=colors.HexColor("#ff4d4d") if report_data.get('is_scam') else colors.HexColor("#00ff88"))

    # Header
    story.append(Paragraph("ScamGuard AI - Security Intelligence Report", title_style))
    story.append(Paragraph(f"Analysis ID: #{report_id} | Date: {report_data.get('timestamp')}", styles['Normal']))
    story.append(Spacer(1, 20))

    # Safety Grade Section
    story.append(Paragraph("Safety Grade", header_style))
    story.append(Paragraph(report_data.get('grade', 'N/A'), grade_style))
    
    grade_footer_style = ParagraphStyle('GradeFooter', parent=styles['Italic'], alignment=1)
    story.append(Paragraph("A: Low Risk | B: Moderate | C: High | D: Critical", grade_footer_style))
    story.append(Spacer(1, 20))

    # Analysis Summary Table
    summary_data = [
        ["Audit Category", "Detection Result"],
        ["Threat Classification", "MALICIOUS" if report_data.get('is_scam') else "SAFE / VERIFIED"],
        ["Probability Score", f"{report_data.get('confidence', 0)*100:.2f}%"],
        ["Entity Verification", report_data.get('company', 'Unknown')],
        ["Entity Status", report_data.get('company_status', 'N/A')]
    ]
    
    t = Table(summary_data, colWidths=[200, 300])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#4e54c8")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor("#e0e0e0")),
        ('PADDING', (0, 0), (-1, -1), 10)
    ]))
    story.append(t)
    story.append(Spacer(1, 24))

    # AI Explanation
    story.append(Paragraph("AI Pattern Diagnostics:", header_style))
    story.append(Paragraph(report_data.get('explanation', 'No explanation provided.'), styles['Normal']))
    story.append(Spacer(1, 15))

    # Risk Factors
    factors = report_data.get('factors', [])
    if factors:
        story.append(Paragraph("Detected Risk Indicators:", header_style))
        for factor in factors:
            story.append(Paragraph(f"• [!] {factor}", styles['Normal']))
        story.append(Spacer(1, 15))

    # Extracted Text (Truncated for report)
    story.append(Paragraph("Source Text Snippet:", header_style))
    content_preview = report_data.get('content', '')[:1000] + ("..." if len(report_data.get('content', '')) > 1000 else "")
    story.append(Paragraph(content_preview, ParagraphStyle('Small', parent=styles['BodyText'], fontSize=8, textColor=colors.grey)))

    # Disclaimer
    story.append(Spacer(1, 30))
    story.append(Paragraph("DISCLAIMER: This report is generated by an AI model and should be used as a guidance tool only. Always perform manual due diligence before sharing sensitive information.", ParagraphStyle('Tiny', parent=styles['Italic'], fontSize=7, textColor=colors.grey)))

    doc.build(story)
    return filename
